# if
[isnull]
body = """
if ($0 === null) {
\t$1
}\
"""

[notnull]
body = """
if ($0 !== null) {
\t$1
}\
"""

# function
[fn]
body = """
function $0($1) {
\t$2
}\
"""

# util

[log]
body = """
console.log($0)
"""

[getid]
body = """
document.getElementById($0)
"""

[for]
body = """
for(let ${1:i} = ${2:0}; $1 < ${3:n}; $1++) {
\t$0
}\
"""
